"""more updates(order item)

Revision ID: 05f636fcb68b
Revises: da91e32ff186
Create Date: 2026-09-18 14:30:19.004095

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f636fcb68b'
down_revision = 'da91e32ff186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('escrow_fee', sa.Numeric(precision=12, scale=2), server_default='500.00', nullable=False))
    op.add_column('orders', sa.Column('in_transit_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'in_transit_at')
    op.drop_column('orders', 'escrow_fee')
    # ### end Alembic commands ###
