"""init product order orderitem

Revision ID: 4b3e0dfc5e7b
Revises: 
Create Date: 2026-08-27 19:32:20.262137

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3e0dfc5e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('delivery_recipient_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_phone', sa.String(length=50), nullable=True),
    sa.Column('delivery_address_line1', sa.String(length=255), nullable=False),
    sa.Column('delivery_address_line2', sa.String(length=255), nullable=True),
    sa.Column('delivery_city', sa.String(length=120), nullable=False),
    sa.Column('delivery_state', sa.String(length=120), nullable=True),
    sa.Column('delivery_postal_code', sa.String(length=30), nullable=True),
    sa.Column('delivery_country', sa.String(length=120), nullable=False),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('paystack_reference', sa.String(length=255), nullable=True),
    sa.Column('paystack_access_code', sa.String(length=255), nullable=True),
    sa.Column('paystack_authorization_url', sa.String(length=1024), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_orders_total_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_guest_email'), 'orders', ['guest_email'], unique=False)
    op.create_index('ix_orders_paystack_reference', 'orders', ['paystack_reference'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inventory_count', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('inventory_count >= 0', name='ck_products_inventory_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_products_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_items_order_product')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_paystack_reference', table_name='orders')
    op.drop_index(op.f('ix_orders_guest_email'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
