"""optimize users

Revision ID: 7953c9bf59b3
Revises: 7cb691f72d7a
Create Date: 2026-09-05 21:16:22.987003

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7953c9bf59b3'
down_revision = '7cb691f72d7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_created_id_desc', 'users', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_id_desc', table_name='users')
    # ### end Alembic commands ###
