"""optimize

Revision ID: 7cb691f72d7a
Revises: 793709c4958a
Create Date: 2026-09-05 20:59:24.955142

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb691f72d7a'
down_revision = '793709c4958a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_created_id_desc', 'orders', ['created_at', 'id'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_products_created_id_desc', 'products', ['created_at', 'id'], unique=False)
    op.create_index('ix_products_desc_trgm', 'products', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_products_owner_created', 'products', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_products_price_id_desc', 'products', ['price', 'id'], unique=False)
    op.create_index('ix_products_title_trgm', 'products', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_reviews_created_id_desc', 'reviews', ['created_at', 'id'], unique=False)
    op.create_index('ix_reviews_product_created', 'reviews', ['product_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_product_created', table_name='reviews')
    op.drop_index('ix_reviews_created_id_desc', table_name='reviews')
    op.drop_index('ix_products_title_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_products_price_id_desc', table_name='products')
    op.drop_index('ix_products_owner_created', table_name='products')
    op.drop_index('ix_products_desc_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_products_created_id_desc', table_name='products')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index('ix_orders_created_id_desc', table_name='orders')
    # ### end Alembic commands ###
