"""update

Revision ID: 84a018cc15c0
Revises: 7953c9bf59b3
Create Date: 2026-09-10 16:59:21.506795

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a018cc15c0'
down_revision = '7953c9bf59b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
