"""add users, product owner, order user linkage

Revision ID: 9ed4e7477971
Revises: 4b3e0dfc5e7b
Create Date: 2026-08-29 06:52:48.270507

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed4e7477971'
down_revision = '4b3e0dfc5e7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SELLER', 'SUPER_ADMIN', name='user_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('orders', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_foreign_key(
        'fk_orders_user_id_users', 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('products', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_foreign_key(
        'fk_products_owner_id_users', 'products', 'users', ['owner_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_owner_id_users', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_column('products', 'owner_id')
    op.drop_constraint('fk_orders_user_id_users', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_column('orders', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
