"""add user default delivery details

Revision ID: ad8167e8ccdf
Revises: 95eba297a277
Create Date: 2026-08-29 19:49:44.100948

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8167e8ccdf'
down_revision = '95eba297a277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_recipient_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('default_phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('default_address_line1', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('default_address_line2', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('default_city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('default_state', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('default_postal_code', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('default_country', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('default_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_notes')
    op.drop_column('users', 'default_country')
    op.drop_column('users', 'default_postal_code')
    op.drop_column('users', 'default_state')
    op.drop_column('users', 'default_city')
    op.drop_column('users', 'default_address_line2')
    op.drop_column('users', 'default_address_line1')
    op.drop_column('users', 'default_phone')
    op.drop_column('users', 'default_recipient_name')
    # ### end Alembic commands ###
