"""more updates in product details

Revision ID: b5c9f626763b
Revises: 05f636fcb68b
Create Date: 2026-09-18 16:15:08.007672

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c9f626763b'
down_revision = '05f636fcb68b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gallery_images', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('products', sa.Column('specifications', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'gallery_images')
    # ### end Alembic commands ###
