"""update on the models and apis

Revision ID: d3af344da389
Revises: ad8167e8ccdf
Create Date: 2026-09-05 08:04:51.879689

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3af344da389'
down_revision = 'ad8167e8ccdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_source', sa.String(length=20), server_default='ONLINE', nullable=False))
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('discount_percentage', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), server_default='15', nullable=False))
    op.add_column('products', sa.Column('tag', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_tag'), 'products', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_tag'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'tag')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'discount_percentage')
    op.drop_column('products', 'original_price')
    op.drop_column('products', 'category')
    op.drop_column('orders', 'order_source')
    # ### end Alembic commands ###
