"""more updates(sku)

Revision ID: da91e32ff186
Revises: 84a018cc15c0
Create Date: 2026-09-18 11:24:18.142382

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da91e32ff186'
down_revision = '84a018cc15c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
